### ISSUE TITLE
Properly enable OAuth2 authorization on springbox-reviews

### ISSUE THREAD

**Issue by mstine** [mstine/springbox-cloud#1]
The `io.springbox.reviews.controllers.ReviewController` controller currently has 3 endpoints:
1. _GET_ `/reviews`
2. _GET_ `/reviews/{mlId}`
3. _POST_ `/reviews`

The first two endpoints should be accessible without authentication or authorization. The last endpoint should require a proper OAuth2 token.

**Comment by viniciusccarvalho** [comment]
Tested Matt, this one was easy, you had all in place :) thanks. Just commented out and tested it. ready to go.

**Comment by mstine** [comment]
Awesome.

On Tue, Apr 28, 2015 at 1:57 PM, Vinicius Carvalho <notifications@github.com

> wrote:
> 
> Tested Matt, this one was easy, you had all in place :) thanks. Just
> commented out and tested it. ready to go.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mstine/springbox-cloud/issues/1#issuecomment-97170170
> .

## 

Matt Stine (@mstine)
matt.stine@gmail.com
