### ISSUE TITLE
Properly pass through OAuth2 token from API Gateway via RestTemplate to Recommendations service for likes

### ISSUE THREAD

**Issue by mstine** [mstine/springbox-cloud#4]
https://github.com/mstine/springbox-cloud/blob/master/springbox-api-gateway/src/main/java/io/springbox/apigateway/services/recommendations/RecommendationsIntegrationService.java#L41 is trying to determine if the current `userName` "likes" the movie in question.

The associated endpoint in `springbox-recommendations` will be secured based on #2. 

According to Syer, you should be able to inject an `OAuth2RestOperations` and that will pass on the current token. However, I'm not sure if that will also have the `RibbonInterceptor`, so we may need to do the Ribbon lookup manually. 

Resolving this issue should determine what will work and implement it.

**Comment by viniciusccarvalho** [comment]
fixed using 
@LoadBalanced
@Autowired
OAuth2RestOperations restTemplate
