### ISSUE TITLE
Clean up the AngularJS application

### ISSUE THREAD

**Issue by mstine** [mstine/springbox-cloud#5]
This code is currently in `springbox-api-gateway/src/main/resources/static/js/hello.js`. 

Should be given a proper name obviously.

Also - I am _not_ a strong JS or Angular developer, so this could use some general love from @scottfrederick.

**Comment by scottfrederick** [comment]
- [x] rename `hello.js` to `app.js`
- [x] rename angular app from `hello` to `springbox`
- [x] split angular controllers into separate .js files that match partials that use them
